appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: az4jkLP6q3zUZtnda4TzNdlOHLR4pgO8NjC8oRgwRYR3ODM8XD0oYNmxLiV6GzvOU9sz7nIrPj8J+28WyANCpXHLdk6UOuNAtBMcuMdIS7S7CdWM1qCNCF+6SLdgKbDjYNztg3e0BdbaexjhH/UAUmHzSNyuJvn6rZGdX0Yz+GRfwJkCW1ULBi4X+U5vOxi4lcaLe3CYOSfzVmhwAvevR6rjRFNkm49TCosv7kGJ1vMKz/W3mpaEEOLUVys6P3FQXM+toa3mxHuAOt4iZCeyY89FrxK5pLzbiHTvoFg2B9ogCpukM6FHe8ugTLam+GzQR0Tu+ugYYSLnEpdHnrZbOeEOmpLNGpMSMI77R73Tp2Xza31B4D/s2R9sQ7TW1quLfEA30kc7lobMnnWBiqg9eCRm+z2G7SA9YipY6jZMSJ5uxW0S8GN6lRziSJk/ksy213vRUk1GtUd0LFTF7+ajXXgf0qr9GCn81FrBu8c8pQNAN5mzsLhmVkvdc6u6WaPAvaBfDIzuvM7UAAhHhslnsNVs0k4XQLnBASdz445LHGmzmmUzw6Z/lYdO71eHc53bW6GoNJP4KK0z9NWMQuK5rrONFhXtdwPUGKArc4mqZ8/KF7wYPJoxk5BdnhrtJeHIssIcnQrlPicnTKsSgmhBTVp8Nqqw+8SRfrFrZmFNWMI=}
provider:
  win: azure
bot:
  automerge: true
